// Generated by LiveScript 1.2.0
var MongoClient;
MongoClient = require('mongodb').MongoClient;
MongoClient.connect('mongodb://localhost:27017/foo-dev', function(err, db){
  if (err) {
    console.dir(err);
    return;
  }
  console.log('connected');
  db.createCollection('test', function(err, collection){
    var doc;
    if (err) {
      console.dir(err);
      return;
    }
    doc = {
      user: 'Mike',
      role: 'admin'
    };
    collection.insert(doc, {
      w: 1
    }, function(err, result){
      if (err) {
        console.log("error on write");
        console.dir(err);
        return;
      }
      console.log("result");
      return console.dir(result);
    });
    return console.log('end');
  });
  return console.log('the real end');
});